import { StyleSheet } from 'react-native';
import * as colors from '../../helpers/colors';
import * as fonts from '../../helpers/fonts';

export default StyleSheet.create({
    containerScrollView: {
        width: '100%',
        backgroundColor: colors.moco,
    },
    container: {
        alignItems: 'center',
        backgroundColor: colors.moco,
    },
    containerBasicInfo: {
        width: '80%',
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
        margin: 24,
        backgroundColor: colors.white,
        marginTop: 40,
        padding: 12,
        borderRadius: 8,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.3,
    },
    name: {
        fontFamily: fonts.bold,
        fontSize: 20,
    },
    email: {
        fontFamily: fonts.regular,
    },
    image: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 3,
        borderColor: colors.primary,
        margin: 16,
    },
    category: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shortBioInput: {
        width: '100%',
        fontFamily: fonts.light,
        fontSize: 12,
        textAlign: 'center',
        marginTop: 8,
        borderTopWidth: 1,
        borderColor: colors.gray2,
        paddingTop: 8,
        paddingBottom: 8,
    },
    containerHeaderTabs: {
        flex: 1,
        justifyContent: 'space-between',
        marginBottom: 12,
        marginTop: 4,
    },
    containerItemHeaderTabs: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 12,
        backgroundColor: colors.white,
        borderRadius: 46,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowRadius: 2,
        shadowOpacity: 0.2,
    },
    innerItemHeaderTabs: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconCategory: {
        width: 40,
        height: 40,
        backgroundColor: 'transparent',
    },
    textPrimary: {
        fontFamily: fonts.medium,
        fontSize: 14,
        marginBottom: 2,
    },
    textRank: {
        fontFamily: fonts.light,
        fontSize: 14,
    },
    flatListLogs: {
        width: '100%',
        flex: 1,
        height: '100%',
    },
    containerItemTab: {
        flex: 0,
        width: '90%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 12,
        marginLeft: '5%',
        marginRight: '5%',
        backgroundColor: colors.white,
        borderRadius: 8,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.3,
        marginTop: 8,
        marginBottom: 8,
    },
    separator: {
        height: 1,
        width: '80%',
        backgroundColor: colors.gray2,
        marginLeft: '10%',
    },
    containerText: {
        flex: 3,
    },
    primaryTextItemTab: {
        fontSize: 13,
        fontFamily: fonts.medium,
    },
    secondaryTextItemTab: {
        fontSize: 12,
        fontFamily: fonts.light,
    },
    containerPoints: {
        flex: 1,
        paddingLeft: 12,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    textPoints: {
        fontFamily: fonts.regular,
        fontSize: 16,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderRadius: 20,
        width: 40,
        height: 40,
        flex: 0,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 8,
        paddingLeft: 4,
    },
    textAuxPoints: {
        fontFamily: fonts.medium,
        fontSize: 14,
    },
    containerHeader: {
        width: '90%',
        padding: 12,
        flex: 0,
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 8,
        marginLeft: '5%',
        marginRight: '5%',
        marginBottom: 12,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.3,
    },
    textHeader: {
        fontFamily: fonts.light,
        fontSize: 16,
    },
    containerAuxHeader: {
        flexDirection: 'row',
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textAuxHeader: {
        fontFamily: fonts.regular,
        fontSize: 12,
    },
    containerSettings: {
        backgroundColor: colors.grayLight,
    },
    itemSettings: {
        backgroundColor: colors.grayLight,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
        paddingTop: 12,
        paddingBottom: 12,
    },
    label: {
        fontFamily: fonts.medium,
        fontSize: 13,
        paddingLeft: 12,
        paddingRight: 12,
        paddingBottom: 6,
    },
    textInput: {
        fontFamily: fonts.light,
        fontSize: 16,
        paddingLeft: 12,
        paddingRight: 12,
    },
    containerLink: {
        flex: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: colors.grayLight,
        padding: 12,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
    },
    textLink: {
        fontFamily: fonts.medium,
        fontSize: 14,
        paddingRight: 12,
    },
    iconLink: {
        paddingRight: 12,
    },
    separatorSettings: {
        height: 12,
        backgroundColor: colors.gray2,
    },
    iconSettings: {
        position: 'absolute',
        top: 0,
        right: 0,
        padding: 12,
    },
    iconBack: {
        position: 'absolute',
        top: 0,
        left: 0,
        padding: 8,
    },
    containerSelector: {
        flex: 0,
    },
    containerNoLogs: {
        backgroundColor: colors.white,
        borderRadius: 8,
        marginLeft: '5%',
        marginRight: '5%',
        marginBottom: 12,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.3,
        width: '90%',
        padding: 12,
    },
    textNoLogs: {
        fontFamily: fonts.light,
        fontSize: 14,
        width: '100%',
        textAlign: 'center',
        paddingTop: 12,
    },
    containerActionsNoLogs: {
        flex: 1,
        flexDirection: 'row',
        marginTop: 12,
        marginBottom: 12,
    },
    itemActionsNoLogs: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 8,
        borderColor: colors.primary,
        borderRadius: 8,
        borderWidth: 1,
        paddingTop: 12,
        paddingBottom: 12,
    },
    textActionsNoLogs: {
        fontFamily: fonts.regular,
        fontSize: 13,
        color: colors.primary,
    },
});
