import { StyleSheet } from 'react-native';
import * as colors from '../../helpers/colors';
import * as fonts from '../../helpers/fonts';

export default StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        backgroundColor: colors.grayLight,
    },
    containerText: {
        flex: 1,
        alignItems: 'center',
        padding: 40,
        justifyContent: 'flex-start',
        width: '100%',
    },
    textDefault: {
        fontFamily: fonts.black,
        color: colors.white,
        width: '100%',
        textAlign: 'center',
        fontSize: 24,
        backgroundColor: 'transparent',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.5,
    },
    textInputQuestion: {
        fontFamily: fonts.medium,
        marginBottom: 20,
        shadowColor: colors.black,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.7,
    },
    textInputAnswer: {
        fontSize: 16,
        color: colors.black,
        textAlign: 'left',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        flex: 0,
        justifyContent: 'center',
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 12,
        paddingRight: 12,
        borderRadius: 16,
        backgroundColor: 'transparent',
        fontFamily: fonts.regular,
    },
    answerContainer: {
        borderRadius: 16,
        borderColor: colors.primary,
        borderWidth: 4,
        backgroundColor: colors.white,
        marginTop: 10,
        marginBottom: 10,
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        position: 'relative',
        shadowColor: colors.black,
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowRadius: 5,
        shadowOpacity: 0.2,
        width: '100%',
    },
    imageBackground: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        zIndex: -1,
    },
    points: {
        fontFamily: fonts.black,
        fontSize: 20,
        width: '100%',
        textAlign: 'center',
    },
    pointsAux: {
        fontFamily: fonts.medium,
        fontSize: 14,
        width: '100%',
        textAlign: 'center',
    },
    containerFooter: {
        backgroundColor: colors.white,
        position: 'absolute',
        bottom: 0,
        borderTopWidth: 1,
        borderColor: colors.gray2,
        padding: 12,
        flex: 0,
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        marginRight: 8,
    },
    containerTextFooter: {
        flex: 1,
    },
    containerNumChapters: {
        flex: 0,
        paddingLeft: 16,
    },
    textNumChapters: {
        fontFamily: fonts.medium,
        fontSize: 13,
        marginTop: 4,
    },
    textPrimaryFooter: {
        fontFamily: fonts.medium,
        fontSize: 13,
    },
    textAuxFooter: {
        fontFamily: fonts.light,
        fontSize: 11,
    },
    containerNext: {
        flex: 0,
        flexDirection: 'row',
        paddingRight: 12,
        width: '100%',
        justifyContent: 'flex-end',
    },
    textNext: {
        color: colors.primary,
        textAlign: 'right',
        fontFamily: fonts.light,
        fontSize: 16,
        paddingRight: 4,
    },
    containerLastChapter: {
        paddingTop: 24,
        margin: 12,
        borderTopWidth: 1,
        borderColor: colors.gray2,
    },
    textLastChapter: {
        fontFamily: fonts.light,
        marginLeft: 8,
        fontSize: 14,
        marginRight: 12,
    },
    listItemLastChapter: {
        justifyContent: 'flex-start',
        flex: 1,
        flexDirection: 'row',
        paddingBottom: 26,
    },
    containerLinkLastChapter: {
        flex: 0,
        justifyContent: 'center',
        paddingBottom: 24,
        paddingTop: 24,
    },
    containerRating: {
        width: '100%',
        flex: 0,
        justifyContent: 'center',
        flexDirection: 'row',
    },
    textLinkLastChapter: {
        width: '100%',
        textAlign: 'center',
        fontFamily: fonts.light,
        fontSize: 16,
        color: colors.primary,
    },
    containerQuestion: {
        padding: 12,
        paddingTop: 32,
    },
    textQuestion: {
        fontFamily: fonts.light,
        fontSize: 18,
        width: '100%',
        textAlign: 'center',
        paddingTop: 12,
        paddingBottom: 24,
    },
    containerAnswer: {
        paddingBottom: 12,
    },
    textAnswer: {
        width: '100%',
        textAlign: 'center',
        fontFamily: fonts.light,
        fontSize: 16,
        color: colors.primary,
    },
    containerPopup: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 12,
    },
    emojiPopup: {
        fontSize: 40,
        marginBottom: 12,
    },
    textH1Popup: {
        fontSize: 16,
        textAlign: 'center',
        color: colors.black,
        fontFamily: fonts.medium,
        marginBottom: 8,
    },
    textPopup: {
        fontSize: 14,
        textAlign: 'center',
        color: colors.black,
        fontFamily: fonts.light,
    },
    buttonPopup: {
        fontSize: 16,
        color: colors.primary,
        fontFamily: fonts.light,
    },
    containerIconClose: {
        position: 'absolute',
        top: 28,
        right: 12,
        zIndex: 1,
    }
});
