# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'



target 'girlscode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  # pod 'Firebase/Crash'
  pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  # react-native-image-crop-picker
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  #Also add this at the very bottom of your Podfile

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  # Pods for girlscode

  target 'girlscodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'girlscode-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for girlscode-tvOS

  target 'girlscode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
