import { StyleSheet } from 'react-native';
import * as colors from '../../../helpers/colors';
import * as fonts from '../../../helpers/fonts';

export default StyleSheet.create({
    containerMain: {
        backgroundColor: colors.grayLight,
        flex: 1,
    },
    containerFlatList: {
        width: '100%',
        flex: 1,
        marginBottom: 52,
        paddingBottom: 12,
    },
    headerGallery: {
        flex: 0,
        justifyContent: 'space-between',
        flexDirection: 'row',
        paddingTop: 24,
    },
    containerGallery: {
        width: '100%',
        height: '100%',
    },
    textHeaderGallery: {
        padding: 8,
        fontSize: 16,
        color: colors.primary,
    },
    chapter: {},
    inputTitle: {
        width: '100%',
        paddingTop: 24,
        paddingBottom: 32,
        paddingLeft: 12,
        paddingRight: 12,
        fontSize: 24,
        fontFamily: fonts.bold,
        textAlign: 'left',
    },
    containerSeparator: {
        flex: 0,
        justifyContent: 'space-between',
        width: '100%',
        flexDirection: 'row',
        marginTop: 24,
        marginBottom: 24,
    },
    containerPointSeparator: {
        flex: 0,
        justifyContent: 'center',
        flexDirection: 'row',
    },
    pointSeparator: {
        width: 6,
        height: 6,
        borderRadius: 4,
        backgroundColor: colors.gray2,
        marginLeft: 8,
        marginRight: 8,
    },
    containerInputText: {
        paddingLeft: 12,
        paddingRight: 12,
        position: 'relative',
        marginBottom: 12,
    },
    inputText: {
        fontSize: 18,
        lineHeight: 40,
        fontFamily: fonts.light,
    },
    emojiInputText: {
        position: 'absolute',
        top: 4,
        left: 12,
    },
    containerQuestion: {
        marginTop: 24,
        marginBottom: 24,
        marginLeft: 12,
        marginRight: 12,
        backgroundColor: colors.white,
        borderColor: colors.gray2,
        borderWidth: 1,
        borderRadius: 8,
        paddingTop: 16,
        paddingBottom: 16,
        position: 'relative',
    },
    iconRemoveQuestion: {
        position: 'absolute',
        top: 0,
        right: 0,
        zIndex: 2,
        padding: 12,
    },
    inputQuestion: {
        paddingLeft: 12,
        paddingRight: 12,
        fontSize: 18,
        fontFamily: fonts.light,
        textAlign: 'center',
        width: '100%',
        marginBottom: 16,
    },
    containerAnswer: {
        borderTopWidth: 1,
        borderColor: colors.gray2,
        padding: 12,
    },
    mediaAnswer: {
        flex: 0,
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    iconAnswer: {
    },
    inputAnswer: {
        marginLeft: 12,
        fontSize: 16,
        fontFamily: fonts.regular,
        width: '100%',
    },
    containerEmoji: {
        fontSize: 32,
        width: '100%',
        textAlign: 'center',
    },
    containerErrorText: {
        padding: 12,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: colors.red,
        borderStyle: 'dashed',
        marginTop: 16,
    },
    containerTextErrorText: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        width: '100%',
    },
    emojiErrorText: {
        fontSize: 24,
    },
    textErrorText: {
        marginLeft: 8,
        marginRight: 12,
        color: colors.red,
        fontSize: 12,
        width: '85%',
        fontFamily: fonts.regular,
    },
    inputErrorText: {
        marginTop: 12,
        fontSize: 16,
        fontFamily: fonts.regular,
        width: '100%',
        textAlign: 'center',
    },
    defaultImage: {
        backgroundColor: colors.white,
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emojiDefaultImage: {
        fontSize: 32,
    },
    textDefaultImage: {
        fontFamily: fonts.regular,
        color: colors.gray2,
        marginTop: 12,
        fontSize: 16,
    },
    image: {
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
    },
    containerButton: {
        margin: 12,
    },
    emojiButton: {
        fontSize: 24,
        position: 'absolute',
        left: 12,
        top: 10,
        zIndex: 1,
        backgroundColor: 'transparent',
    },
    containerAddQuestion: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        paddingLeft: 12,
        paddingRight: 12,
        alignItems: 'center',
    },
    emojiAddQuestion: {
        fontSize: 16,
    },
    textAddQuestion: {
        fontSize: 18,
        fontFamily: fonts.light,
        color: colors.orange,
        marginLeft: 2,
    },
    textToPublish: {
        borderColor: colors.blue,
        backgroundColor: colors.white,
        color: colors.blue,
    },
    textButton: {
        height: 52,
        borderWidth: 2,
        borderRadius: 8,
        flex: 0,
        padding: 12,
        width: '100%',
        textAlign: 'center',
        fontFamily: fonts.regular,
        fontSize: 14,
        paddingTop: 16,
    },
    containerHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        justifyContent: 'space-between',
        paddingTop: 20,
        width: '100%',
        flexDirection: 'row',
        flex: 0,
        zIndex: 1,
        height: 64,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
    },
    textHeader: {
        color: colors.primary,
        backgroundColor: 'transparent',
        padding: 12,
    },
    containerMetrics: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        padding: 12,
    },
    containerMetric: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginLeft: 12,
        backgroundColor: 'transparent',
    },
    emojiMetric: {
        fontSize: 18,
    },
    textMetric: {
        fontFamily: fonts.regular,
        fontSize: 14,
    },
    containerFooter: {
        position: 'absolute',
        zIndex: 1,
        bottom: 0,
        width: '100%',
        height: 52,
        left: 0,
        backgroundColor: colors.white,
        flex: 0,
        justifyContent: 'space-between',
        flexDirection: 'row',
        borderTopWidth: 1,
        borderColor: colors.gray2,
        alignItems: 'center',
    },
    containerImage: {
        position: 'relative',
        borderTopWidth: 0.5,
        borderBottomWidth: 0.5,
        borderColor: colors.gray2,
    },
    containerChapterH: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingLeft: 12,
        paddingRight: 12,
        paddingTop: 24,
        paddingBottom: 16,
    },
    textChapterH: {
        fontFamily: fonts.regular,
        fontSize: 20,
    },
    containerAddChapter: {
        paddingLeft: 12,
        paddingRight: 12,
    },
    textAddChapter: {
        borderColor: colors.primary,
        color: colors.primary,
        fontFamily: fonts.regular,
    },
    // containerChapter: {
    //     position: 'absolute',
    //     top: -12,
    //     width: '100%',
    //     justifyContent: 'center',
    //     zIndex: 1,
    //     flex: 1,
    //     alignItems: 'center',
    //     backgroundColor: 'transparent',
    // },
    // containerTextChapter: {
    //     height: 24,
    //     borderWidth: 1,
    //     borderColor: colors.gray2,
    //     backgroundColor: colors.white,
    //     borderRadius: 12,
    // },
    // textChapter: {
    //     backgroundColor: 'transparent',
    //     fontFamily: fonts.bold,
    //     fontSize: 12,
    //     textAlign: 'center',
    //     width: 'auto',
    //     padding: 4,
    //     paddingRight: 16,
    //     paddingLeft: 16,
    // },
});
