import { StyleSheet } from 'react-native';
import * as colors from '../../../helpers/colors';
import * as fonts from '../../../helpers/fonts';

export default StyleSheet.create({
    containerMain: {
        backgroundColor: colors.grayLight,
        flex: 1,
    },
    headerGallery: {
        flex: 0,
        justifyContent: 'space-between',
        flexDirection: 'row',
        paddingTop: 24,
    },
    containerGallery: {
        width: '100%',
        height: '100%',
    },
    textHeaderGallery: {
        padding: 8,
        fontSize: 16,
        color: colors.primary,
    },
    inputTitle: {
        width: '100%',
        paddingTop: 24,
        paddingBottom: 24,
        paddingLeft: 12,
        paddingRight: 12,
        fontSize: 24,
        fontFamily: fonts.bold,
        textAlign: 'left',
    },
    lineSeparator: {
        borderBottomWidth: 1,
        borderColor: colors.gray2,
        width: '35%',
        height: 12,
    },
    textSeparator: {
        fontFamily: fonts.bold,
        fontSize: 12,
        padding: 4,
        width: '30%',
        textAlign: 'center',
        height: 24,
        color: colors.black,
    },
    containerSeparator: {
        flex: 0,
        justifyContent: 'space-between',
        width: '100%',
        flexDirection: 'row',
        marginTop: 12,
        marginBottom: 12,
    },
    inputText: {
        paddingLeft: 12,
        paddingRight: 12,
        fontSize: 18,
        lineHeight: 28,
        fontFamily: fonts.light,
    },
    containerQuestion: {
        marginTop: 24,
        marginBottom: 24,
        marginLeft: 12,
        marginRight: 12,
        backgroundColor: colors.white,
        borderColor: colors.gray2,
        borderWidth: 1,
        borderRadius: 8,
        paddingTop: 16,
        paddingBottom: 16,
        position: 'relative',
    },
    iconRemoveQuestion: {
        position: 'absolute',
        top: 0,
        right: 0,
        zIndex: 2,
        padding: 12,
    },
    inputQuestion: {
        paddingLeft: 12,
        paddingRight: 12,
        fontSize: 16,
        fontFamily: fonts.bold,
        textAlign: 'center',
        width: '100%',
        marginBottom: 16,
    },
    containerAnswer: {
        borderTopWidth: 1,
        borderColor: colors.gray2,
        padding: 12,
    },
    mediaAnswer: {
        flex: 0,
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    iconAnswer: {
    },
    inputAnswer: {
        marginLeft: 12,
        fontSize: 16,
        fontFamily: fonts.regular,
        width: '100%',
    },
    containerEmoji: {
        fontSize: 32,
        width: '100%',
        textAlign: 'center',
    },
    containerErrorText: {
        padding: 12,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: colors.red,
        borderStyle: 'dashed',
        marginTop: 16,
    },
    containerTextErrorText: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        width: '100%',
    },
    emojiErrorText: {
        fontSize: 24,
    },
    textErrorText: {
        marginLeft: 8,
        marginRight: 12,
        color: colors.red,
        fontSize: 12,
        width: '85%',
        fontFamily: fonts.regular,
    },
    inputErrorText: {
        marginTop: 12,
        fontSize: 16,
        fontFamily: fonts.regular,
        width: '100%',
        textAlign: 'center',
    },
    defaultImage: {
        backgroundColor: colors.white,
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderTopWidth: 1,
        borderColor: colors.gray2,
    },
    emojiDefaultImage: {
        fontSize: 32,
    },
    textDefaultImage: {
        fontFamily: fonts.regular,
        color: colors.gray2,
        marginTop: 12,
        fontSize: 16,
    },
    image: {
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
    },
    containerButton: {
        margin: 12,
    },
    emojiButton: {
        fontSize: 24,
        position: 'absolute',
        left: 12,
        top: 10,
        zIndex: 1,
        backgroundColor: 'transparent',
    },
    textAddQuestion: {
        borderColor: colors.secondary,
        backgroundColor: colors.white,
        color: colors.secondary,
    },
    textToPublish: {
        borderColor: colors.blue,
        backgroundColor: colors.white,
        color: colors.blue,
    },
    textButton: {
        height: 52,
        borderWidth: 2,
        borderRadius: 8,
        flex: 0,
        padding: 12,
        width: '100%',
        textAlign: 'center',
        fontFamily: fonts.bold,
        fontSize: 14,
        paddingTop: 16,
    },
    containerHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        justifyContent: 'space-between',
        paddingTop: 20,
        width: '100%',
        flexDirection: 'row',
        flex: 0,
        zIndex: 1,
        height: 64,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderColor: colors.gray2,
    },
    textHeader: {
        color: colors.primary,
        backgroundColor: 'transparent',
        padding: 12,
    },
    containerMetrics: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        padding: 12,
    },
    containerMetric: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginLeft: 12,
        backgroundColor: 'transparent',
    },
    emojiMetric: {
        fontSize: 18,
    },
    textMetric: {
        fontFamily: fonts.regular,
        fontSize: 14,
    },
    containerFooter: {
        position: 'absolute',
        zIndex: 1,
        bottom: 0,
        width: '100%',
        height: 52,
        left: 0,
        backgroundColor: colors.primary,
    },
    textAddChapter: {
        borderWidth: 0,
        borderRadius: 0,
        color: colors.white,
    },
});
